# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
ZSH_THEME="af-magic-custom"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git docker docker-compose screen nvm kubectl autojump)

# Customize to your needs...

# OSX
if [[ `uname` == 'Darwin' ]] ; then
  # MacPorts
  export PATH=/opt/local/bin:/opt/local/sbin:$PATH
  export MANPATH=/opt/local/share/man:$MANPATH
  # Python (installed by MacPorts)
  py_bin="/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin"
  [ -d $py_bin ] && export PATH=$py_bin:$PATH
  # CUDA
  cuda_dir="/usr/local/cuda"
  cudnn_dir="/Developer/NVIDIA/cuDNN-v5.1"
  [ -d $cuda_dir ] && \
    export PATH="$cuda_dir/bin":$PATH && \
    export CUDA_HOME="$cuda_dir" && \
    export DYLD_LIBRARY_PATH="$CUDA_HOME/lib:$CUDA_HOME:$CUDA_HOME/extras/CUPTI/lib${DYLD_LIBRARY_PATH:+:${DYLD_LIBRARY_PATH}}"
  [ -d $cudnn_dir ] && \
    export DYLD_LIBRARY_PATH="$cudnn_dir/lib":$DYLD_LIBRARY_PATH
  [ -n "${DYLD_LIBRARY_PATH}" ] && \
    export LD_LIBRARY_PATH=$DYLD_LIBRARY_PATH
fi

# 256 color support
if [ -n "$TMUX" ]; then
  # For tmux
  export TERM=screen-256color
else
  export TERM=xterm-256color
fi

if [[ -d "~/.dircolors" && ! -L "~/.dircolors" ]] ; then
  eval `dircolors ~/.dircolors`
fi

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export EDITOR="vim"

# Ruby
[ -s "$HOME/.rvm" ] && . "$HOME/.rvm/scripts/rvm"

# Node
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Golang
[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"

source $ZSH/oh-my-zsh.sh

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/Dev/google-cloud-sdk/path.zsh.inc" ]; then source "$HOME/Dev/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/Dev/google-cloud-sdk/completion.zsh.inc" ]; then source "$HOME/Dev/google-cloud-sdk/completion.zsh.inc"; fi
